
export const GLOBAL_DATA = 'GLOBAL_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const GLOBAL_STEPPER_DATA = 'GLOBAL_STEPPER_DATA';
export const DELETE_STEPPER_DATA = 'DELETE_STEPPER_DATA';
export const SET_ORGANISATION_DROPDOWN_VALUES = 'SET_ORGANISATION_DROPDOWN_VALUES';
